### ISSUE TITLE
Add validation/constraint for statewide incarceration rate calculation

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#100]
Currently, we do not place any constraint on the month over month values for the Statewide Incarceration Rate. This can result in the 
The proposed solution would be to create a floor for the % of the **population** (not % counties) represented in the calculation for any given month; data points below this floor would be omitted from the graph. The floor should be based on realistic numbers, and could be derived in a few ways (non-exhaustive): 
- 2SD below average % population represented *across* all states
- 2SD below average % population represented **in the state of interest (across all data points)**
- 2SD below average % population represented **in the state of interest, only in the given time range selected in the graph.**

**Comment by hobuobi** [comment]
Update: Chatted with @colincadams and I think we can set an arbitrary floor for this in the meantime (e.g. 10% population covered). We will do more research into the population coverage later and pick a more informed floor!

This ticket should now be actionable!

**Comment by nasaownsky** [comment]
Closed by #106
