### ISSUE TITLE
Add the Last Updated date to the header.

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#101]
We should include the date that the data was last ingested as the "Last Updated" date for a given state. 

A few things to resolve before this can be worked on: 
- We would need to pipe this information into the data file for each state. 
- Since this will be different for Jails vs Corrections, we will need to either: 
    - Change the header text to correspond with the system selection (Corrections or Jails). 
    - Put this somewhere other than the header (e.g. a single line of text just above the "Key Insights" section. 
- Anything else @colincadams?

**Comment by nasaownsky** [comment]
@colincadams should I use for this `date_published` field?

**Comment by colincadams** [comment]
Yep! Since we already do this on each metric block, I think the real change here is to take the maximum `date_published` across a tab. Then put that either in the header or the Sources section (pending @hobuobi)

**Comment by hobuobi** [comment]
Agreed with the approach! 
Proposed solution is to put this in the header text on a new line, for example: 

> _Last updated: January 29, 2021 (Corrections) and March 30, 2021 (Jails)_

<img width="853" alt="Screen Shot 2021-05-06 at 11 57 10 AM" src="https://user-images.githubusercontent.com/7134733/117351122-325e4900-ae62-11eb-847e-c850beccb98e.png">

**Comment by jessex** [comment]
Closed by #107
