### ISSUE TITLE
Merge Jails functionality into the main branch

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#102]
At this point, I think we are ready to merge the functionality for the Jails features into the main branch! Excellent work. 

If any changes are necessary that would need to go to the Corrections-only version of the site that state DOCs are currently reviewing, @colincadams will cherrypick them in.

**Comment by colincadams** [comment]
Oops, I added this to the list but @jessex was ahead of us and already filed #93, closing this as a dupe.
