### ISSUE TITLE
Add warning if percentage covered is different for statewide population vs incarceration rate

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/justice-counts-components#104]
**Is your feature request related to a problem? Please describe.**

Currently it is possible that a different set of counties is used when calculating the statewide incarceration rate vs the jail population. This can cause confusion as key insights can show a high coverage percentage, but the state-wide jail population will be low.

**Describe the solution you'd like**

If either of the percentage_covered values for the state wide jail population are different than incarceration rate, add the following warning tooltip to the statewide jail population card:

"This value covers XX percent of counties, representing about XX percent of the state population."

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by nasaownsky** [comment]
@colincadams Maybe this warning should appeal to the Incarceration Rate card? Cause if not this warning will just duplicate Counties Reporting card caption since we use the same values there.

**Comment by colincadams** [comment]
Ah I had it backward in my head and thought the key insights was currently showing percentage covered for incarceration rate, not for jail population.

I'll defer to @hobuobi for the final call, but I am tempted to say we should switch it, and have the percentage covered card show the percentage covered for incarceration rate, and put the warning on the Jail Population card. The percentage covered for Incarceration Rate will always be the same or higher than for Jail Population, so this ensures that the percentage covered shown in the card is the highest we have and aligns with the graph down below.

**Comment by hobuobi** [comment]
I agree with the proposed approach!

**Comment by colincadams** [comment]
fixed by #109
