### ISSUE TITLE
Adjustments to tooltip text

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/justice-counts-components#105]
**What needs to be done? Why does it need to be done?**

The scope of information that we have included in the tooltips has grown significantly since we started, so I wanted to start by recapping my understanding of the logic rules for when each piece of text should be included in a tooltip:

* Info (only show if we have data)
  * **Source Info Text**
  * **Last Updated Text**
* Warning (only show if one of these is non-empty)
  * if there is no data for this metric on either tab: **Not Available Text**
  * else
    * if the most recent data point is outside range: **Too Stale Text** 
    * if data for this metric is newer on the other tab
      * if there is data for this metric on this tab: **Restricted Text**
      * else: **Other Frequency Text**
      * **Use Switch Text**

I think this mostly aligns with how it is currently implemented, but calling it out in case it is useful in simplifying any of the current logic.

We need to refine the text in the tooltips to handle cases where data is provided directly to CSG instead of pulled from a publicly available report. The changes needed for that are:

* Source Info:
  * if there is a report url:
    * "Sourced from ${source}'s public reports."
  * else: 
    * "Sourced from data provided to the CSG Justice Center by ${source}."
  * "Includes data for the following categories: ${categories}"
  * "(${report})" (without link if there is no report url)
* Too Stale:
  * "This data is available in a public report from" -> "This data is available from"
* Other Frequency:
  * "(Monthly|Annual) data is not available in a public report from" -> "(Monthly|Annual) data is not available from"

cc @hobuobi 

**Additional context**
Add any other context about the task here.

**Comment by nasaownsky** [comment]
@colincadams How I should distinguish where data is provided directly to CSG instead of pulled from a publicly available report?

**Comment by colincadams** [comment]
Sorry I didn't call that out very directly -- if the `source_url` field in the data file will is an empty string then the data was provided directly to CSG
