### ISSUE TITLE
Provide context on which populations are averages

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#110]
We need to indicate which population metrics are averages. I can think of two possible approaches: 
1- Add the calculation type ("point in time" or "average") to the tooltip somewhere (next to or below the "Last Updated" info?) 
2- Add an asterisk (*) to the metric label (e.g. "Probation Population*") only if the measurement is an average; include a line at the bottom of the flow chart that says something like " * These metrics are reported as averages in the available reports."
3- Add a line to the Methodology section noting that X Y Z metrics are reported as averages. (e.g. "Probation Population and Parole Population are reported here as averages").

@colincadams for thoughts on what makes sense and would have the easiest implementation!

**Comment by colincadams** [comment]
I think adding it to the tooltip is likely the easiest, we already have that setup to be completely dynamic so adding an additional case there should be straightforward.

We will have to add more information to the data files for this one. I haven't updated the fixture file yet, but I will add a new column called `measurement_type` that can contain the following values: [`INSTANT`, `AVERAGE`, `DELTA`, `PERSON_BASED_DELTA`]. These can be handled generically, although in practice the first two will be used for population data and the latter two will be used for admissions/releases.

@hobuobi to adjust the text, but my initial thought for the text for each case:
* INSTANT: "point in time"
* AVERAGE: "average" (or "daily average"?)
* DELTA: omit the text entirely
* PERSON_BASED_DELTA: omit the text entirely

This will be added to all three metric data files (both corrections files and the jails file, not the counties data file).
