### ISSUE TITLE
State-specific context for DE and ME (abolishment of parole)

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#126]
Some states (DE, ME, amongst others) have explicitly abolished parole. We need to add some context to each of these pages to make it clear that parole-related metrics will not appear in these dashboards. 

**Partially blocked** on CSG sending us the specific copy that they'd want. 
[UPDATE 8/2] CSG sent the copy! It is rather simple:
- “Note: Delaware abolished parole in 1990.”
- “Note: Maine abolished parole in 1976.”

P0: Add this text to the bottom of the header text for each relevant state page.

**Comment by jessex** [comment]
@hobuobi are there examples of state-specific methodology text like this in the app already? It sounds like this is not just new text but a new feature request to enable state-specific additions like this.

**Comment by hobuobi** [comment]
This would probably require some new functionality to be built, yes; I don't believe we have this yet. The need has come up before though, so I think @colincadams has already thought about how it might be done in case his input is helpful here!

**Comment by colincadams** [comment]
#123 added support for adding to copy to the description of a particular state. Currently this is just used for unified states like this:

<img width="971" alt="Screen Shot 2021-07-27 at 1 21 57 PM" src="https://user-images.githubusercontent.com/3762913/127222218-d607a0d3-4449-47c0-a2fa-0c37d190eab9.png">

If the copy for abolishing parole can go there as well, it should be pretty straightforward to add on to that. If it needs to go elsewhere then that would need to be built separately.

**Comment by jessex** [comment]
Thanks, @colincadams!

Just to make sure, @hobuobi, you want this new copy that CSG is going to send us to be in the text at the top of the page right? As long as that's true and that copy can be appended to the end of the normal text (i.e. where "This state operates..." starts above), then no special work is necessary beyond just including this new copy as a possibility.

**Comment by jessex** [comment]
Any update, @hobuobi?

**Comment by hobuobi** [comment]
1. Yes, we should be able to do this at the top of the page! 
2. Unfortunately we haven't received the new copy from CSG yet. I asked them about it earlier today/Thursday and so they should be sending that over soon; if it needs to happen next week, I think that should be okay from a timeline perspective.

**Comment by hobuobi** [comment]
[UPDATE 8/2] CSG sent the copy! It is rather simple:
- “Note: Delaware abolished parole in 1990.”
- “Note: Maine abolished parole in 1976.”
And it is confirmed that we can put it in the header.
