### ISSUE TITLE
Explain monthly vs annual discrepancies

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#127]
Currently, we have a "Data Aggregation Range" control that allows the user to switch between monthly and annualized metrics. 

Because of the methodology that we calculate the metrics that populate the page, we occasionally run into cases where a metric that we would expect to show up in the annual view (as an aggregation of monthly counts or otherwise) does not actually show up. 

The initial solution is to simply include language in the description of the Data Aggregation Range control ("Use the control below to...") to make sure that users understand why some metrics might not show up. 

- @colincadams to provide more context (and possibly draft up the language, since he knows the cases and methodology best). Please comment to this thread!
- @jessex or @hobuobi to implement (should be a simple text change). 

As a follow-up, we might want to revisit the methodology used to avoid these confusions altogether.

**Comment by jessex** [comment]
I'm happy to make the text change once I've got the text from @colincadams!

**Comment by hobuobi** [comment]
Bump on @colincadams to pose some draft text!

**Comment by colincadams** [comment]
Added some draft text to this doc: https://docs.google.com/document/d/1ohrCBZY7Alkwf4WKihIyrX-cRgkMv8IAL8TDKeA6JhI/edit?usp=sharing

This includes both (1) proposed copy changes to the switch itself and (2) longer methodology to be included elsewhere on the site (with the metric definitions, perhaps?)

**Comment by jessex** [comment]
@hobuobi can you comment here when the copy in Colin's doc has been approved? And also where it has been decided that longer methodology text should be incorporated?

**Comment by jessex** [comment]
Any update, @hobuobi?

**Comment by hobuobi** [comment]
Still pending CSG review. However, I think we might end up moving this to a separate page on the Justice Counts website that doesn't need to be in our application, which would put the implementation burden on their webmaster. I'll try to confirm this today!

**Comment by colincadams** [comment]
Should we change this to just cover the text change to the switch included in the doc?

**Comment by colincadams** [comment]
I updated the switch text with what was in the doc. The rest of the copy will go in a separate page to be implemented by CSG.

If CSG has copy edits for the switch text, we can make those changes as part of a separate ticket filed for their edits.
