### ISSUE TITLE
Disable data aggregation switch when no data available.

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#130]
We currently have a single state that has NO monthly data at all (Idaho). However, you can still technically view the monthly tab, and it shows... absolutely nothing. (See image below)

![Screen Shot 2021-07-26 at 11 36 28 AM](https://user-images.githubusercontent.com/7134733/127040863-e80febbe-9002-4ce7-a67c-6784c3e97cab.png)

The desired behavior would be to disable the data aggregation switch: 
- Don't allow the user to switch from the tab that actually has data (Annual). 
- Change the cursor to something that indicates that you can't click it (maybe "not-allowed"). 
- Add "no data" to the tab that does not have data (e.g. "Monthly (no data)"). 

**NOTE: ** @colincadams was already working on this and wants to finish it!

**Comment by jessex** [comment]
Any update on this one, @colincadams?

**Comment by colincadams** [comment]
Sorry for the hold up, just sent #132
