### ISSUE TITLE
Ensure a great mobile experience

### ISSUE THREAD

**Issue by jessex** [Recidiviz/justice-counts-components#14]
**Is your feature request related to a problem? Please describe.**
Data visualization and exploration can be tricky on mobile, but are important to get right for apps and tools that are available to the general public, as this one will be.

**Describe the solution you'd like**
Ensure that the component works as mocked and described in the PRD on mobile devices.

**Describe alternatives you've considered**
N/A

**Additional context**
We are specifically interested in:
- Chrome on Android
- Safari on iOS

We should test in Browserstack or other equivalent tools.

**Comment by Wmaileq** [comment]
I think this issue is no longer the issue, as no mobile mockups present in the Figma and mobile UI was made previously in #18.

**Comment by jessex** [comment]
Good point. I just double-checked with Product to see if they ever developed mobile-specific mocks. If not, we'll just close this and let final testing determine if any further UI/UX changes are needed. Will follow-up here once I've heard back.

**Comment by jessex** [comment]
@Wmaileq, just a heads up that I spoke with Product and they do have mobile-specific mocks coming to that PRD soon. If the PRD and mocks haven't been updated by the time you get started on Thursday, then here's a quick note about what is to come in case it's helpful, "The main thing I think we'd still want to fix is the flowchart -- basically making it a single column (P0) and leaving room on the sides for the arrows (P1)." If that's not enough to go by, then I'd wait until the PRD and mocks are updated before getting started.

**Comment by hobuobi** [comment]
@Wmaileq , I've tagged you in a comment on the document! As Josh mentioned, the major change here is with the flowchart, which should be implemented as a single column with arrows occasionally going out to the sides, as shown below. 
Everything else looked great on the mobile experience -- thank you for that!
<img src ="https://user-images.githubusercontent.com/7134733/103922121-2d61d680-50c8-11eb-93bc-2d784894ec87.png" width="250px">
