### ISSUE TITLE
Copy change requests 

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#143]
_Below includes some copy changes requested from CSG._

- The language at the top of each state page should read as follows: 
> “The following is a broad overview of the available data from corrections and jail systems agencies in (X State), using the most up-to-date publicly available data to show the latest trends in across key indicators. The purpose of this page is to (A) consolidate data from several sources to provide policymakers with timely information on criminal justice trends at the state and local -levels and (B) to identify and highlight agencies that are reporting this important data publicly.”
 

- On the jails tab, for the first line chart, the “statewide confinement rate” data title to the right of the graph should be changed to “State (Reporting Counties) Confinement Rate”

- The “Sources” language at the bottom of the Jails page should read as follows: 
> This dashboard is powered by data compiled by the Vera Institute of Justice (Vera Jails Survey) and Bureau of Justice Statistics (BJS) (Annual Survey of Jails). Data from Vera is continuously integrated from January 2020 onwards, while BJS data is pulled in manually as reports are published with the most recent report showing 2018 data. Note that this leads to a gap in data in 2019, as BJS data is forthcoming.
 
- When you have the option to switch counties, the language in the pop up should read as follows: 
> Select a county below and click “View County” to see the trend of the county’s jail confinement rate over time. Counties are arranged in alphabetical order. Some counties cannot be selected due to missing data; see FAQs and Methodology for more details.
 
- For the following states, please add this note to the language at the top of the page (similar to how we did DE and ME):
    - IA- Note: Iowa reports their prison population daily, but we do not currently have the ability to capture that data.
    - MN- Note: Minnesota reports their prison population daily, but we do not currently have the ability to capture that data.
    - NM-  Note: New Mexico reports their prison population daily, but we do not currently have the ability to capture that data.
    - ND- Note: North Dakota reports their prison population daily, but we do not currently have the ability to capture that data.

**Comment by jessex** [comment]
@hobuobi, this should be ready to go! Take a quick look at the PR and I'll merge it.
