### ISSUE TITLE
Data format should be JSON Lines, not regular JSON

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/justice-counts-components#35]
**Describe the bug**

Currently the app expects data to be in regular JSON format, like what is in [src/data.json](https://github.com/Recidiviz/justice-counts-components/blob/main/src/data.json). However, it should instead expect the data in JSON lines format so that it conforms with our other products (e.g. [JSON files in pulse-data](https://github.com/Recidiviz/pulse-dashboard/tree/master/server/core/demo_data)) and can be hooked up directly to BigQuery exports in the future. 

**To Reproduce**
1. Replace `src/data.json` with the [fixture file](https://drive.google.com/file/d/1V8PfIjfsFzft0_nOmdZOZGtQGqwJm5xC/view)
1. Run the app
1. See error

```
./src/data.json
Module parse failed: Unexpected token { in JSON at position 377 while parsing near '...hange":0.013487476}
{"state_code":"US_AK...'
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
SyntaxError: Unexpected token { in JSON at position 377 while parsing near '...hange":0.013487476}
{"state_code":"US_AK...'
    at JSON.parse (<anonymous>)
```

**Expected behavior**

It should instead load the data

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

**Comment by jessex** [comment]
@Wmaileq I saw that you moved on to some of the V2 Jails work. But we want to circle back here and finish this one on Monday since it might be the last ticket before we can release V1!
