### ISSUE TITLE
Provide updated fixture file(s) to support Jails view

### ISSUE THREAD

**Issue by jessex** [Recidiviz/justice-counts-components#39]
**Is your feature request related to a problem? Please describe.**
To support the new Jails view bootstrapped in #38, we'll need new or updated fixture data files for the repository to read.

**Describe the solution you'd like**
We should either:
1. Update the existing data file so that it includes corrections and jails data, or
2. Create another data file that is used specifically for jails data

I imagine number 2 is the right path here because I don't think there's much of a need for data sharing/reuse across the two views, but I leave that to the backend team to conclude.

**Describe alternatives you've considered**
N/A

**Additional context**
See the new "Category 2: Jails" section of [the PRD](https://docs.google.com/document/d/1eOiMzk8_eDjC4W0xn89qlkmj_6SOqi1dBTyEusAGGaI/edit?ts=5fb45edc#heading=h.s7ludzwvb7fe), particularly the "Metrics to Show" sub-section.

**Comment by colincadams** [comment]
Note: This will also need to include a file with all counties in each state (state_code, county_code, readable_name) to power the county selector

**Comment by colincadams** [comment]
I have created two additional fixtures (one for metric data, one for county names) and added them to the folder here:
https://drive.google.com/drive/folders/14F6VQfXQbIXWLRfjM8lc7xf_coyJYivr?usp=sharing

I also added some description at the end of the fixture file document: https://docs.google.com/document/d/14RZM1KchEnMrc19vpr_kKxWE3bY2BhGzoMEP37Fra30/edit#heading=h.6gz7jlt22qlp

They may change slightly as some of the open questions on the PRD are resolved, but in general they should be ready to build off of! Let me know if anything seems amiss or if there are changes that would make them easier to integrate with.
