### ISSUE TITLE
Support key insights cards for new Jails view

### ISSUE THREAD

**Issue by jessex** [Recidiviz/justice-counts-components#40]
**Is your feature request related to a problem? Please describe.**
As described in the new "Category 2: Jails" section of [the PRD](https://docs.google.com/document/d/1eOiMzk8_eDjC4W0xn89qlkmj_6SOqi1dBTyEusAGGaI/edit?ts=5fb45edc#heading=h.s7ludzwvb7fe), we are going to create a new Jails view alongside the existing Corrections view. The top section of this view, just below the new tab selector from #38, is a set of key insight cards about the jails system.

**Describe the solution you'd like**
The design of these cards is identical to the key insight cards from the existing corrections view. But the actual metrics shown are different, and one of these cards does _not_ have a percentage change component, so that will need to be supported.

Additionally, the captions below the cards are a bit more variable and less formulaic than they were in the corrections view.

**Describe alternatives you've considered**
N/A

**Additional context**
See the new "Category 2: Jails" section of [the PRD](https://docs.google.com/document/d/1eOiMzk8_eDjC4W0xn89qlkmj_6SOqi1dBTyEusAGGaI/edit?ts=5fb45edc#heading=h.s7ludzwvb7fe) and the Figma mocks it links to.

**Comment by colincadams** [comment]
Note the fixture files to support these is now linked from #39
