### ISSUE TITLE
Support graphs in new Jails view

### ISSUE THREAD

**Issue by jessex** [Recidiviz/justice-counts-components#41]
**Is your feature request related to a problem? Please describe.**
As described in the new "Category 2: Jails" section of [the PRD](https://docs.google.com/document/d/1eOiMzk8_eDjC4W0xn89qlkmj_6SOqi1dBTyEusAGGaI/edit?ts=5fb45edc#heading=h.s7ludzwvb7fe), we are going to create a new Jails view alongside the existing Corrections view. The middle section of the view, just below the key insight cards created in #40, is a pair of graphs describing jail incarceration rates.

**Describe the solution you'd like**
The design of these graphs is identical to the graphs from the existing corrections view. But the actual metrics shown are different.

Furthermore, one of these graphs has a new link that opens a modal and lets you select from a list of counties in the state. The functionality for that new button and modal will be handled in a separate ticket (#42), so this ticket should just get the graph operational with "the default" county selected (should be the first one in alphabetical order; see comments in the graphs sub-section of this part of the PRD) and skip the county selector for now.

**Describe alternatives you've considered**
N/A

**Additional context**
See the new "Category 2: Jails" section of [the PRD](https://docs.google.com/document/d/1eOiMzk8_eDjC4W0xn89qlkmj_6SOqi1dBTyEusAGGaI/edit?ts=5fb45edc#heading=h.s7ludzwvb7fe) and the Figma mocks it links to.

**Comment by colincadams** [comment]
Note the fixture files to support these is now linked from #39

**Comment by jessex** [comment]
This is done on the `v2-jails` branch which will be merged back to `main` after our V1 release has been finalized. Closing this out.
