### ISSUE TITLE
Support the sources section at the bottom of the Jails view

### ISSUE THREAD

**Issue by jessex** [Recidiviz/justice-counts-components#43]
**Is your feature request related to a problem? Please describe.**
As described in the new "Category 2: Jails" section of [the PRD](https://docs.google.com/document/d/1eOiMzk8_eDjC4W0xn89qlkmj_6SOqi1dBTyEusAGGaI/edit?ts=5fb45edc#heading=h.s7ludzwvb7fe), we are going to create a new Jails view alongside the existing Corrections view. The bottom section of this view is a Sources section very similar to the Sources section at the bottom of the Corrections view.

**Describe the solution you'd like**
The structure and copy is identical to the sources section from the existing corrections view. The actual data sources it points to will be different but this should be supported by the existing structure of the sources component, I believe. We should just test and ensure that this is working as expected and matches the latest mocks.

**Describe alternatives you've considered**
N/A

**Additional context**
See the new "Category 2: Jails" section of [the PRD](https://docs.google.com/document/d/1eOiMzk8_eDjC4W0xn89qlkmj_6SOqi1dBTyEusAGGaI/edit?ts=5fb45edc#heading=h.s7ludzwvb7fe) and the Figma mocks it links to.

**Comment by nasaownsky** [comment]
So, @jessex, I figure out how Sources in the App works, and its require some source fields in fixture files that not exist in Jails data file. PRD says TBD for this section. What should I do?

**Comment by colincadams** [comment]
This looks like it is complete!
