### ISSUE TITLE
Off-by-one error in date calculation for tooltips

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#55]
Reported dates all seem to be off by -1 day, which can cross a month or even a year boundary if the actual date was the first of the month. In the example below, the date reported should be **November 30, 2020**, not November 29, 2020. 

This might actually be a data issue (assigning to @colincadams to investigate). 
<img width="952" alt="Screen Shot 2021-02-08 at 3 52 00 PM" src="https://user-images.githubusercontent.com/7134733/107659258-d063be00-6c3b-11eb-8167-081a325969e2.png">

**Comment by colincadams** [comment]
Noted in #57 but there was both a data issue (-98%) and some frontend bugs behind this!
