### ISSUE TITLE
Dates in flow diagram are too misaligned

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#56]
Current behavior for the flow diagram displays the most recent data for each metric block. However, we realized that we run into some cases in which the dates for the data being displayed is very misaligned; for example, in Nebraska the prison data is from 2020, probation is from 2017, and parole is from 2013, and revocations are from 2020. 

We have a few options to fix this: 
1) Place new restrictions on the data that can be displayed in the flow diagram; in order to show up in the flow diagram, the latest data for a given metric in the diagram must be **within one year** of the most recently reported metric in the diagram. If this is the case, we will need to indicate this somehow ("Data is too stale to display"). 
2) Indicate the dates associated with each metric on the corresponding metric block. This will require a slight redesign of the metric blocks. 

We still need to decide which option to go with, so this ticket is probably not actionable until we decide. @macfarlandian FYI.

**Comment by hobuobi** [comment]
Update: The second suggestion (adding the date range to metric blocks) is now covered in #70. However, after consulting with @macfarlandian , I think we should still try to do the first suggestion ("the latest data for a given metric in the diagram must be within one year of the most recently reported metric in the diagram").

**Comment by nasaownsky** [comment]
@hobuobi, about first suggestion: if we have most recently reported metric within range `November 2020 (compared to November 2019)` the latest data for the stale metric in the diagram must be earlier than `November 2018`, I guess?

**Comment by hobuobi** [comment]
The date range for the stale metric needs to overlap with the primary date range (in this case, Nov 2019 and Nov 2020). A few examples:
- April 2020 (compared to April 2019) -- GOOD
- November 2019 (compared to November 2018) -- GOOD
- October 2019 (compared to October 2018) -- BAD, DO NOT SHOW

Tagging @macfarlandian again to confirm that this is ideal. 

Also noting that we should probably explain this somewhere so that people don't think that the data doesn't exist at all; I might come back to this with a visual treatment.

**Comment by jessex** [comment]
@hobuobi I want to confirm that you actually want to go through with this ticket. Your description mentioned two options, the PR that Ilya has filed is for the first option listed, but late last week he did what seems to me like the second option in #74 (adding a date range to each metric block). Since your description includes, "We still need to decide which option to go with," I want to make sure we actually want to do both of these options.
