### ISSUE TITLE
[Corrections] Handle no data for state

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/justice-counts-components#60]
**Describe the bug**

There are two states that we don't expect there to be data for at least in the near term, UT and WY. We should handle this case.

**To Reproduce**
1. Set `stateCode` to US_WY
2. Observe 'undefined' and 'Infinity' throughout

**Expected behavior**

@hobuobi to define.

Most of the components handle no data gracefully, but when there is no data at all for a state then we can't define the default time range (e.g. November 2020 -- compared to November 2019). The easiest thing is likely to come up with alternative text for each place that this is displayed.

Alternatively, we could have a separate treatment for the whole page, e.g. no public data sources were found for [state].

**Screenshots**

<img width="1041" alt="Screen Shot 2021-02-12 at 10 43 27 AM" src="https://user-images.githubusercontent.com/3762913/107809098-6d4b5780-6d1f-11eb-99c1-7c86787eadf9.png">

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

**Comment by hobuobi** [comment]
Behavior should be as shown below! Suppress all components other than the header and description, and replace the description text with the following: 

No data was publicly available for this state. If you are a representative of this state and would like to contribute your data to this site, please [contact us.](https://justicecounts.csgjusticecenter.org/stay-in-touch/)

![Webpage (1)](https://user-images.githubusercontent.com/7134733/107815146-d20ab000-6d27-11eb-920c-545da0762271.jpg)

**Comment by colincadams** [comment]
@hobuobi it looks like the "Stay In Touch" page only allows you to subscribe. Probably fine as a placeholder for now, but eventually should we replace this link?

**Comment by colincadams** [comment]
@Wmaileq I think we can proceed with the link as is for now, and look at replacing it in the future
