### ISSUE TITLE
Small copy changes

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#66]
Change introductory text (top of the page) to: 
"The following is a broad overview of the corrections system in [state], representing the latest data available and indicating changes over the course of the prior year."

In Flow Diagram: 
- "Prison Sentences" to **“New Prison Commitments”**
- “Probation Sentences” to **“New Probation Commitments”**

In Graphs, "Admissions":
- "New Commitments" to **“New Prison Commitments”**

**Comment by nasaownsky** [comment]
Hey, @hobuobi! In Graph `Admissions to Prison` no such field as `New Commitments`. What did you mean?

**Comment by hobuobi** [comment]
Sorry -- in that Graph, I meant "New Court Admissions" to “New Prison Commitments”
