### ISSUE TITLE
Add "Last Updated" date to each metric block tooltip.

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#67]
We should start showing the date that we last updated the data for a given metric in the tooltips that we already provide. This should look something like what is shown below (Figma mockup https://www.figma.com/file/66HyjH0efZMoAuTlhnojWh/Justice-Counts-Report?node-id=977%3A814): 

<img width="607" alt="Screen Shot 2021-03-05 at 11 26 45 AM" src="https://user-images.githubusercontent.com/7134733/110164652-82f3f000-7da6-11eb-97c4-a92cdb465a63.png">

For now, this should use the date that the data was ingested into our database (@colincadams to provide this in the fixture file). In the future, we can move to using the actual collection date, as this will be a more accurate reflection of the freshness of the data.

**Comment by nasaownsky** [comment]
Hey @colincadams, please provide this date in the fixture file. Thanks!

**Comment by colincadams** [comment]
Uploaded the new file with an additional column `date_published`. Let me know if it doesn't work as expected!

https://drive.google.com/file/d/1UUpyZMSVyJMJzgjrJnGGA3GixIamoq4y/view?usp=sharing

**Comment by nasaownsky** [comment]
@colincadams could you please also add that column to corrections file?
