### ISSUE TITLE
Visual design bugs

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#68]
See here for full details and screenshots: https://www.figma.com/file/66HyjH0efZMoAuTlhnojWh/Justice-Counts-Report?node-id=964%3A712

List of fixes: 
- Color of headers (currently #000) should be #132536
- Background color for tooltips should be #082249
- Color of "Courts" and "Corrections" labels should be #B8BFC6
- Color of "Not Available" headers and other text should be #808C99
- Margin on mobile cuts off some content (see screenshot in Figma) 
- Orange links in tooltips should not be double-underlined when active (see screenshot) 

@agr0n for any further details and clarifications.

**Comment by nasaownsky** [comment]
Also, some of the issues are already fixed. Maybe you having old version, @hobuobi? Anyway I created PR, so take a look.
