### ISSUE TITLE
Errors when only county level jail population is present in data

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/justice-counts-components#77]
**Describe the bug**

We have the calculations working for county level jail population, but when wiring up the frontend with just this information it fails to render.

**To Reproduce**
1. Checkout `v2-jails` (at 39e66e8f)
2. Replace `src/data/jails_data.json` with https://drive.google.com/file/d/1p5w9jSHHy4rZpkxVrtZk2cFVOcof8mpF/view?usp=sharing
3. Run `yarn start`

**Expected behavior**

The page should render with just the available data shown.

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

<img width="1062" alt="Screen Shot 2021-03-23 at 12 04 01 PM" src="https://user-images.githubusercontent.com/3762913/112203517-dc925200-8bcf-11eb-8fbb-d4eda69cf7d1.png">

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: MacOS
 - Browser [e.g. chrome, edge]: chrome
 - Version [e.g. 22]: 39e66e8f

**Additional context**

**Comment by nasaownsky** [comment]
@colincadams, I found it! The old jails file contains `percentage_change` and stuff except `value` only if there is no `county_code`. So logic was based on this rule. The new file instead not includes lines without `county_code`. So I don't get it honestly. If we delete that rule it means that `Key Insights` would only display data for last county in alphabetical order since there is no common fields.

**Comment by colincadams** [comment]
Right, this is a small subset of the data that we will actually show on the site when it goes live. It only has county specific data, but we aren't calculating the state level data yet. For right now, this is all the data that the calculations are producing, and it would be great if we could still have the site functional with that set of the data for testing and validating.

Key Insights should continue to only show data from lines without `county_code`. If there are no lines without `county_code` then Key Insights should just be blank. We have similar logic in the corrections side where if there is no data for a metric it is omitted from Key Insights. Do you think that will work and be straightforward to do?

**Comment by nasaownsky** [comment]
Yes, I think that this will work. Few remarks: 
1. New file contains only `POPULATION_JAIL` metric, but we do not display this elsewhere but Key Insights, so with this file Jails view would not display any data at all
2. With adding new states and counties for that states be sure to update County Name file so the app would work correctly.

**Comment by colincadams** [comment]
Added this to the PR but adding it here as well, here is the file with the full list of county names and resident populations: https://drive.google.com/file/d/1Mg6Q0jUBTocFjMpBfSMucXdKDFl33rP6/view?usp=sharing
