### ISSUE TITLE
Port data CSV file into app and integrate with interactive elements

### ISSUE THREAD

**Issue by jessex** [Recidiviz/justice-counts-components#8]
**Is your feature request related to a problem? Please describe.**
As described in the [PRD](https://docs.google.com/document/d/1eOiMzk8_eDjC4W0xn89qlkmj_6SOqi1dBTyEusAGGaI/edit?ts=5fb45edc#heading=h.44wxoacjibhb), we need to integrate the JSON Lines file (one json object per row) that contains the data to be used by the app components.

**Describe the solution you'd like**
We've been provided with a description of the JSON Lines data file and an example version. We should place that example file at the root of the repository and document its specification in the README (similar to what we did in the supervision-success-component with the projection model input).

This will also include integrating the data from the JSON Lines file with all three components: Key Insights, Flowchart, and Graphs. All dynamic text should come from the file at this point. In short, this task wires together all of the elements into a working prototype.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jessex** [comment]
The final version of the data file has been made available in the previously shared "JC - Fixture File" doc. That should be ready to use now!

**Comment by Wmaileq** [comment]
@jessex I've just checked the fixture file and found no difference with the previous version.

**Comment by jessex** [comment]
Okay cool, good to know. I wasn't sure when the last time you saw it was so just wanted to make sure you knew it was in its final state.
