### ISSUE TITLE
Prevent selecting a county that does not have data in county selector.

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#85]
Currently, regarding the county selector in the top graph: 
1- A user can select a county that has no data for the given range. 
2- The user also cannot tell which counties do or do not have data.

Both of these can cause unnecessary confusion for the user and should be resolved. The proposed solution would simply be to prevent the selection of those counties, and indicate this through the visual design and interactions. 

![Frame 763 (5)](https://user-images.githubusercontent.com/7134733/114640314-b1f26100-9c84-11eb-8aea-53cf9df235de.png)

In the new modal, counties that have no data should be grayed out as shown. Upon hover, the highlight should be gray, and should **not** allow the user to select the county (the cursor should stay the same, instead of turning into a "pointer"). 

--

@colincadams -- are there edge cases here that we might want to be aware of? One that I can think of is if there is no data in the current time range, someone might select a county but then not see any data when the modal is closed -- might want to consider adding a warning in the legend or something to indicate this? 

@agr0n -- does the design of this look okay to you? Any suggested changes (visually, interactively, copy, etc)?

**Comment by jessex** [comment]
Closed by #86
