### ISSUE TITLE
Add new lines to the "Releases" graph.

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#87]
Currently, we only show releases to liberty in the "Releases" time series graph. This is currently just labeled as "Releases" in the legend. 

We should expand the graph and legend to include **releases to parole**. In doing so, we will also need to add more detail in the legend by specifically labeling these as "Releases to Liberty" and "Releases to Parole". 

![Slice 1 (10)](https://user-images.githubusercontent.com/7134733/116184574-e29ab780-a6d4-11eb-82ab-ad471021ec45.png)

@colincadams to add more detail on how these will appear in the fixture file.

**Comment by colincadams** [comment]
The mapping for these should be:

* "Releases to Liberty": `RELEASES_COMPLETED`
* "Releases to Parole": `RELEASES_TO_PAROLE`

`RELEASES_TO_PAROLE` is already in the fixture file so you should be good to go!
