### ISSUE TITLE
Create the "reporting counties" modal.

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#88]
Currently, in the Jails view, we do not allow someone to easily see which counties are reporting data on a steady cadence. To fix this, we will add the following: 

1- A simple modal that shows a list of all the counties that are reporting. This modal should be nearly identical to the "county selector" modal in its design (see below). 

![Jails, Counties Reporting View](https://user-images.githubusercontent.com/7134733/116184651-0958ee00-a6d5-11eb-99bd-bd5c7dae06bc.png)

2- A link in the caption of the "Counties Reporting" key insights block that opens that modal. The text for this should now read as follows. 
> Currently, about XX% of counties report their jail populations on at least a monthly basis, representing about YY% of the state population. See full list of counties **here.** 
![Slice 1 (11)](https://user-images.githubusercontent.com/7134733/116184691-1d9ceb00-a6d5-11eb-8eac-52fd69c203da.png)

(Clicking "here" should open the modal.)

**Comment by jessex** [comment]
@hobuobi one question after reviewing @nasaownsky's PR: this new modal is very similar to the existing county selector modal, and in #89 you've asked that we add a strikethrough treatment for unavailable counties in that county selector. Do you want that same strikethrough treatment in this reporting counties modal for consistency? That's how Ilya has it right now (strikethrough in both) but I see from the mocks that you didn't explicitly call for a strikethrough here, so what would you prefer?

Also, I see that the copy here includes "See Methodology for ..." but I'm not 100% sure that refers to. Is Methodology a page that is going to be provided directly by CSG that we should make linkable, or is it referring to the Source section at the bottom of the page, or am I missing something basic?

**Comment by jessex** [comment]
Also, @hobuobi, related to that second question: I see that #89 contains similar text added to the county selector: "see methodology for more details." So my question applies to that "methodology" reference in both places. But also, I see that Methodology is capitalized here on this ticket but lower-cased on #89. Is that a typo? Do we want it lower-cased in both places?

**Comment by hobuobi** [comment]
- Oh strange, I must have exported the mocks at slightly different times! Strikethrough in both is preferred, yes. 
- Methodology should be capitalized in both places, and will refer to the Methodology section at the bottom of the page. Also a good reminder for @colincadams and I to eventually write that 😅

**Comment by jessex** [comment]
Closed by #90
