### ISSUE TITLE
[Jails] County Selector tweaks/bugs

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#89]
A number of small changes to the appearance, function, etc. of the county selector: 

- BUG: On mobile, the position of the modal is inconsistent and often appears above or below the fold. 
    - The preferred behavior would be to have the modal appear a consistent distance from the top of the screen and take up most of the screen height (see below). 
<img src="https://user-images.githubusercontent.com/7134733/116266657-89607180-a730-11eb-9de8-be1291738b74.jpeg" width="300px" style="display:inline">

<img src="https://user-images.githubusercontent.com/7134733/116266883-c0cf1e00-a730-11eb-8563-86ac653a134f.png" width="300px" style="display:inline">

- There should be some margin (5px) between the county blocks in the modal. This is most apparent when the blue background of a "hovered" county overlaps with the background of the selected county. 
- For counties that are not available in the county selector, let's 1) strikethrough the text and 2) add a line at the top of the modal that says: "Some counties cannot be selected due to missing data; see methodology for more details." 

![Frame 763 (7)](https://user-images.githubusercontent.com/7134733/116267379-35a25800-a731-11eb-8307-4a06d9d320af.png)

**Comment by jessex** [comment]
Closed by #90
