### ISSUE TITLE
Merge v2-jails into main

### ISSUE THREAD

**Issue by jessex** [Recidiviz/justice-counts-components#93]
**What needs to be done? Why does it need to be done?**
Merge the `v2-jails` branch into the `main` branch to unify the app.

**Additional context**
N/A

**Comment by colincadams** [comment]
@nasaownsky is this already in progress? Not sure how messy the merge will be, but I think this is one of the last items before launch, besides any final copy and polish. Let me know if you need any help here!

**Comment by nasaownsky** [comment]
@colincadams Nope, not in progress.
But if @jessex and @hobuobi agreed, I could launch that.

**Comment by colincadams** [comment]
That would be great! Then we can send off a single unified site to review before launch.

**Comment by hobuobi** [comment]
Agreed, should merge!

**Comment by colincadams** [comment]
Okay @nasaownsky, I thought this might be messy but it is very messy! Let me know if you already have this in progress or if it is something you can tackle in the next day or two, if not I will continue with my attempt!
