### ISSUE TITLE
Various copy tweaks

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#97]
- Change the header text at the top of the page: 
    - "The following is a broad overview of the corrections system in Pennsylvania, representing up-to-date data and changes compared to last year. An additional section on crime indicators will be added at a later date." 
    - Note that the main changes are 1) removing mention of dates, and 2) noting that only the crime indicators are "coming soon". 
- Change the titles for the Jails charts: 
    - "Jail Incarceration Rate" --> "Statewide vs County Incarceration Rates"
    - "Jail Incarceration Rate (Top Counties)" --> "Incarceration Rates for Most Populous Counties" 
- Change the "By Type" subtitle on the right side of the chart headers:  
    - Statewide vs Single County: "(DATE RANGE)"
    - Top Counties: "By County (DATE RANGE)" 
- New copy for the Sources section: 
    - "This dashboard is powered by data compiled by the Vera Institute of Justice (Vera Jails Survey), and Bureau of Justice Statistics (BJS) (Annual Survey of Jails). Data from Vera is continuously integrated from January 2020 onwards, while BJS data is pulled in manually as reports are  published. Note that this leads to a gap in data in 2019, as no BJS Jail Survey has been produced for this year yet.

**Comment by jessex** [comment]
Closed by #103
