### ISSUE TITLE
Change the logic for the default county in the Jails Incarceration Rate graph

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#98]
Currently, the default county is just the first one alphabetically. 

We should change this to default to the top county **by population.** This will better align with the urban centers in the state and is more likely to be populated.

**Comment by colincadams** [comment]
@hobuobi Should this always be the most populous county, even if we don't have data for it? Or should we pick the most populous county for which we do have data?

**Comment by jessex** [comment]
Closed by #103
