### ISSUE TITLE
Add the "% counties reporting" to the Statewide Incarceration Rate tooltip

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#99]
Tooltip should now read: 
- "Statewide (XX% reporting): YYY per 100,000" 

The XX% reporting value should be the percentage of counties used to create that particular calculation. Looking to @colincadams for more details on the data/calculation needs here.

**Comment by colincadams** [comment]
The data needed for this should already be present in the `percentage_covered_county` for each data point that needs it.

For reference, this is the tooltip in question (the one on the graph!)
<img width="1014" alt="Screen Shot 2021-05-04 at 12 39 02 PM" src="https://user-images.githubusercontent.com/3762913/117060730-1b8aeb80-acd6-11eb-9315-5dcdecb4e483.png">

**Comment by jessex** [comment]
Closed by #103
